FROM node:18-alpine
LABEL maintainer="Cato Yeung"

WORKDIR /app

COPY ./package.json ./
RUN npm -g install next
RUN npm install

COPY ./ ./

RUN npm run build
ENV NODE_ENV=development

CMD ["npm", "run" ,"dev"]