version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        - DEV=true
        - DEBUG=true
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - "./backend:/app"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=cashew
      - DB_USER=cashewadmin
      - DB_PASS=cashewp@ssw0rd123
      - USE_PTVSD=true
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cashew
      - POSTGRES_USER=cashewadmin
      - POSTGRES_PASSWORD=cashewp@ssw0rd123

volumes:
  dev-db-data: