# Generated by Django 3.2.20 on 2023-07-12 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LAYOUT', 'LAYOUT'), ('ROUTING', 'ROUTING')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('TEXTFIELD', 'TEXTFIELD'), ('ANCHORED_TEXTFIELD', 'ANCHORED_TEXTFIELD'), ('TABLE', 'TABLE')], max_length=255)),
                ('pages', models.CharField(max_length=255)),
                ('x1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anchor_text', models.CharField(max_length=255, null=True)),
                ('anchor_x1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchor_y1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchor_x2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchor_y2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchored_textfield_x1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchored_textfield_y1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchored_textfield_x2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anchored_textfield_y2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('table_column_xs', models.CharField(max_length=255, null=True)),
                ('last_modified_at', models.DateTimeField()),
                ('anchor_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.rule')),
                ('parser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
                ('parser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_id', to='parsers.parser')),
                ('route_to_parser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_parser_id', to='parsers.parser')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('routing_rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.routingrule')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.rule')),
            ],
        ),
    ]
