# Generated by Django 3.2.20 on 2023-10-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='col_index',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('XML_INTEGRATION', 'XML_INTEGRATION'), ('PDF_INTEGRATION', 'PDF_INTEGRATION')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('xml_path', models.CharField(max_length=1023, null=True)),
                ('template', models.TextField(null=True)),
                ('pdf_version', models.CharField(max_length=255, null=True)),
                ('pdf_path', models.CharField(max_length=1023, null=True)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='parsers.parser')),
            ],
            options={
                'db_table': 'Integrations',
            },
        ),
    ]
