# Generated by Django 3.2.20 on 2023-07-12 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_alter_parser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='anchor_rule',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='anchored_textfield_x1',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='anchored_textfield_x2',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='anchored_textfield_y1',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='anchored_textfield_y2',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='table_column_xs',
        ),
        migrations.AlterField(
            model_name='rule',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
