# Generated by Django 3.2.20 on 2023-10-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_auto_20231009_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='col_indexes',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='col_index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
