# Generated by Django 3.2.20 on 2023-10-09 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20231009_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='col_indexes',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='convert_to_table_by_specify_headers',
            field=models.TextField(blank=True, default='', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=256),
        ),
        migrations.AlterField(
            model_name='stream',
            name='join_string',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='regex',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_class',
            field=models.CharField(choices=[('EXTRACT_FIRST_N_LINES', 'EXTRACT_FIRST_N_LINES'), ('EXTRACT_NTH_LINES', 'EXTRACT_NTH_LINES'), ('REGEX_EXTRACT', 'REGEX_EXTRACT'), ('REGEX_REPLACE', 'REGEX_REPLACE'), ('TRIM_SPACE', 'TRIM_SPACE'), ('REMOVE_TEXT_BEFORE_START_OF_TEXT', 'REMOVE_TEXT_BEFORE_START_OF_TEXT'), ('REMOVE_TEXT_BEFORE_END_OF_TEXT', 'REMOVE_TEXT_BEFORE_END_OF_TEXT'), ('REMOVE_TEXT_AFTER_START_OF_TEXT', 'REMOVE_TEXT_AFTER_START_OF_TEXT'), ('REMOVE_TEXT_AFTER_END_OF_TEXT', 'REMOVE_TEXT_AFTER_END_OF_TEXT'), ('REPLACE_TEXT', 'REPLACE_TEXT'), ('REPLACE_REGEX', 'REPLACE_REGEX'), ('JOIN_ALL_ROWS', 'JOIN_ALL_ROWS'), ('COMBINE_FIRST_N_LINES', 'COMBINE_FIRST_N_LINES'), ('GET_CHARS_FROM_NEXT_COL_IF_REGEX_NOT_MATCH', 'GET_CHARS_FROM_NEXT_COL_IF_REGEX_NOT_MATCH'), ('TRIM_SPACE_FOR_ALL_ROWS_AND_COLS', 'TRIM_SPACE_FOR_ALL_ROWS_AND_COLS'), ('REMOVE_ROWS_WITH_CONDITIONS', 'REMOVE_ROWS_WITH_CONDITIONS'), ('MERGE_ROWS_WITH_CONDITIONS', 'MERGE_ROWS_WITH_CONDITIONS'), ('MERGE_ROWS_WITH_SAME_COLUMNS', 'MERGE_ROWS_WITH_SAME_COLUMNS'), ('REMOVE_ROWS_BEFORE_ROW_WITH_CONDITIONS', 'REMOVE_ROWS_BEFORE_ROW_WITH_CONDITIONS'), ('REMOVE_ROWS_AFTER_ROW_WITH_CONDITIONS', 'REMOVE_ROWS_AFTER_ROW_WITH_CONDITIONS'), ('UNPIVOT_TABLE', 'UNPIVOT_TABLE'), ('MAKE_FIRST_ROW_TO_BE_HEADER', 'MAKE_FIRST_ROW_TO_BE_HEADER'), ('REMOVE_EMPTY_LINES', 'REMOVE_EMPTY_LINES'), ('CONVERT_TO_TABLE_BY_SPECIFY_HEADERS', 'CONVERT_TO_TABLE_BY_SPECIFY_HEADERS')], max_length=256),
        ),
        migrations.AlterField(
            model_name='stream',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.CharField(choices=[('TEXTFIELD', 'TEXTFIELD'), ('TABLE', 'TABLE')], max_length=256),
        ),
        migrations.CreateModel(
            name='StreamCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('column', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.stream')),
            ],
            options={
                'db_table': 'stream_conditions',
            },
        ),
    ]
