# Generated by Django 3.2.20 on 2023-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20230712_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('INPUT_TEXTFIELD', 'INPUT_TEXTFIELD'), ('INPUT_DROPDOWN', 'INPUT_DROPDOWN'), ('TEXTFIELD', 'TEXTFIELD'), ('ANCHORED_TEXTFIELD', 'ANCHORED_TEXTFIELD'), ('TABLE', 'TABLE')], max_length=255),
        ),
    ]
