# Generated by Django 3.2.20 on 2023-07-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_alter_rule_rule_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingcondition',
            old_name='routing_rule_id',
            new_name='routing_rule',
        ),
        migrations.RenameField(
            model_name='routingcondition',
            old_name='rule_id',
            new_name='rule',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='parser_id',
            new_name='parser',
        ),
        migrations.RemoveField(
            model_name='routingrule',
            name='parser_id',
        ),
        migrations.RemoveField(
            model_name='routingrule',
            name='route_to_parser_id',
        ),
        migrations.AddField(
            model_name='routingrule',
            name='parser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parser', to='parsers.parser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routingrule',
            name='route_to_parser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_to_parser', to='parsers.parser'),
            preserve_default=False,
        ),
    ]
