# Generated by Django 3.2.20 on 2023-07-21 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20230712_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.UUID('0dd086e9-bab8-4f60-bc06-bf028853bd83'), max_length=255)),
                ('file', models.FileField(max_length=1023, null=True, upload_to='')),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('GIF', 'GIF'), ('TIFF', 'TIFF')], max_length=255)),
                ('filename_without_extension', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('total_page_num', models.IntegerField()),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='parser',
            name='guid',
            field=models.CharField(default=uuid.UUID('28ea0662-fa70-438f-8d6a-4536b24ab07c'), max_length=255),
        ),
        migrations.AddField(
            model_name='routingcondition',
            name='guid',
            field=models.CharField(default=uuid.UUID('593ea073-1b6b-4d9e-abea-2e0ebc7c3228'), max_length=255),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='guid',
            field=models.CharField(default=uuid.UUID('9a64f53d-fe49-45e3-b561-4b7f2ae39db0'), max_length=255),
        ),
        migrations.AddField(
            model_name='rule',
            name='guid',
            field=models.CharField(default=uuid.UUID('58637920-4333-4b3e-b668-6474be38f2b2'), max_length=255),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.UUID('6219b4bd-0987-481b-ad11-df0d28fc24f3'), max_length=255)),
                ('queue_class', models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('IMPORT', 'IMPORT'), ('PREPROCESSING', 'PREPROCESSING'), ('SPLIT', 'SPLIT'), ('PARSING', 'PARSING'), ('POST_PROCESSING', 'POST_PROCESSING'), ('INTEGRATION', 'INTEGRATION')], max_length=255)),
                ('input_result', models.TextField(default='{}', null=True)),
                ('parsed_result', models.TextField(default='{}', null=True)),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='parsers.document')),
                ('parser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.parser')),
            ],
            options={
                'db_table': 'TB_Queues',
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_num', models.IntegerField()),
                ('image_file', models.FileField(max_length=1023, null=True, upload_to='')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('xml', models.TextField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentPages', to='parsers.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser'),
        ),
    ]
