# Generated by Django 3.2.20 on 2023-10-10 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_stream_remove_matched_row_also'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('ocr_type', models.CharField(choices=[('GOOGLE_VISION', 'GOOGLE_VISION')], max_length=255, null=True)),
                ('google_vision_ocr_api_key', models.CharField(max_length=1024, null=True)),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ocrs',
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='queue_status',
            field=models.CharField(choices=[('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('TERMINATED_AFTER_TRIAL', 'TERMINATED_AFTER_TRIAL')], default='READY', max_length=255),
        ),
        migrations.AddField(
            model_name='stream',
            name='unpivot_column_index',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='unpivot_newline_char',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='unpivot_property_assign_char',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='parser',
            name='ocr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsers.ocr'),
            preserve_default=False,
        ),
    ]
