# Generated by Django 3.2.20 on 2023-07-21 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20230721_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='guid',
            field=models.CharField(default=uuid.UUID('3eef7b14-d895-4e0e-8824-953570eea3d1'), max_length=255),
        ),
        migrations.AlterField(
            model_name='parser',
            name='guid',
            field=models.CharField(default=uuid.UUID('c3e8c922-020c-45f8-a1e2-89c27174ace3'), max_length=255),
        ),
        migrations.AlterField(
            model_name='queue',
            name='guid',
            field=models.CharField(default=uuid.UUID('d8924616-715b-4214-a13c-88efb3e3867a'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingcondition',
            name='guid',
            field=models.CharField(default=uuid.UUID('915cfa3e-b65f-4c3e-88c6-4b130b4279e2'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='guid',
            field=models.CharField(default=uuid.UUID('5b14302c-9a19-4c8b-958c-495f4f2fd31e'), max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='guid',
            field=models.CharField(default=uuid.UUID('80e6f971-657c-4d25-98a0-65ba555bdd64'), max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='parsers.parser'),
        ),
        migrations.AlterModelTable(
            name='queue',
            table=None,
        ),
    ]
