# Generated by Django 3.2.20 on 2023-10-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_auto_20231010_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='convert_to_table_by_specify_headers',
        ),
        migrations.DeleteModel(
            name='ConvertToTableBySpecifyHeaders',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
