# Generated by Django 3.2.20 on 2023-07-22 02:44

from django.db import migrations, models
import parsers.models.document
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_auto_20230721_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=parsers.models.document.Document.file_upload_to),
        ),
        migrations.AlterField(
            model_name='document',
            name='guid',
            field=models.CharField(default=uuid.UUID('1aad5395-a391-4455-9a94-4f4910eede15'), max_length=255),
        ),
        migrations.AlterField(
            model_name='parser',
            name='guid',
            field=models.CharField(default=uuid.UUID('ba4d9fb2-e2c2-44d4-888f-123cda362c89'), max_length=255),
        ),
        migrations.AlterField(
            model_name='queue',
            name='guid',
            field=models.CharField(default=uuid.UUID('725ab8b8-a2bb-4565-b058-a56346c035ac'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingcondition',
            name='guid',
            field=models.CharField(default=uuid.UUID('b692a7a3-d4c8-4045-9f50-3f4ca36e641d'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='guid',
            field=models.CharField(default=uuid.UUID('40cdda08-5236-4483-835a-cb02a5a85aee'), max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='guid',
            field=models.CharField(default=uuid.UUID('e219d254-370d-439f-a8a2-1f5bf6f3c24a'), max_length=255),
        ),
    ]
