# Generated by Django 3.2.20 on 2023-07-22 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_auto_20230722_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='C:/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='guid',
            field=models.CharField(default=uuid.UUID('dbc2e30b-b46d-4fe6-bf42-f91cd9fc1de6'), max_length=255),
        ),
        migrations.AlterField(
            model_name='parser',
            name='guid',
            field=models.CharField(default=uuid.UUID('b9e492d6-e757-4ddb-9505-ca7db6a10798'), max_length=255),
        ),
        migrations.AlterField(
            model_name='queue',
            name='guid',
            field=models.CharField(default=uuid.UUID('0b00102f-5e7a-433e-a403-d2758d1a2711'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingcondition',
            name='guid',
            field=models.CharField(default=uuid.UUID('a9cfd8f7-ac31-419f-b527-0d56bf5867e3'), max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='guid',
            field=models.CharField(default=uuid.UUID('8aaa5dea-5c74-4b5b-94c8-c671eb3b0728'), max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='guid',
            field=models.CharField(default=uuid.UUID('2ea1dbed-494b-407e-acb8-bd1a5112bee5'), max_length=255),
        ),
    ]
