# Generated by Django 3.2.20 on 2023-10-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_auto_20231010_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='ocr',
        ),
        migrations.AddField(
            model_name='ocr',
            name='parser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsers.parser'),
            preserve_default=False,
        ),
    ]
