# Generated by Django 3.2.20 on 2023-10-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0009_auto_20231010_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='ocr_type',
            field=models.CharField(choices=[('GOOGLE_VISION', 'GOOGLE_VISION'), ('DOCTR', 'DOCTR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_class',
            field=models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('IMPORT', 'IMPORT'), ('PREPROCESSING', 'PREPROCESSING'), ('OCR', 'OCR'), ('SPLIT', 'SPLIT'), ('PARSING', 'PARSING'), ('POST_PROCESSING', 'POSTPROCESSING'), ('INTEGRATION', 'INTEGRATION')], max_length=255),
        ),
    ]
