# Generated by Django 3.2.20 on 2023-07-22 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0009_auto_20230722_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='parser',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='queue',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='routingcondition',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
