# Generated by Django 3.2.20 on 2023-07-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0010_auto_20230722_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='C:\\Projects\\cashew2\\backend\\backend\\media/documents'),
        ),
    ]
