# Generated by Django 3.2.20 on 2023-07-22 04:10

from django.db import migrations, models
import parsers.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0011_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=parsers.models.document.Document.file_upload_to),
        ),
    ]
