# Generated by Django 3.2.20 on 2023-07-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0012_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_pages', to='parsers.document'),
        ),
    ]
