# Generated by Django 3.2.20 on 2023-10-13 02:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0012_auto_20231012_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splitting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('split_type', models.CharField(choices=[('NO_SPLIT', 'NO_SPLIT'), ('SPLIT_BY_PAGE_NUM', 'SPLIT_BY_PAGE_NUM'), ('SPLIT_BY_CONDITIONS', 'SPLIT_BY_CONDITIONS')], default='NO_SPLIT', max_length=255, null=True)),
                ('parser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'db_table': 'splittings',
            },
        ),
        migrations.CreateModel(
            name='SplittingCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('REGEX', 'REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.rule')),
            ],
            options={
                'db_table': 'splitting_conditions',
            },
        ),
        migrations.CreateModel(
            name='SplittingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('sort_order', models.IntegerField()),
                ('route_to_parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
                ('splitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='parsers.splitting')),
            ],
            options={
                'db_table': 'splitting_rules',
            },
        ),
        migrations.RemoveField(
            model_name='routingrule',
            name='parser',
        ),
        migrations.RemoveField(
            model_name='routingrule',
            name='route_to_parser',
        ),
        migrations.DeleteModel(
            name='RoutingCondition',
        ),
        migrations.DeleteModel(
            name='RoutingRule',
        ),
        migrations.AddField(
            model_name='splittingcondition',
            name='splitting_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_conditions', to='parsers.splittingrule'),
        ),
    ]
