# Generated by Django 3.2.20 on 2023-07-27 03:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0013_alter_documentpage_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('step', models.IntegerField()),
                ('stream_type', models.CharField(choices=[('REGEX_EXTRACT', 'REGEX_EXTRACT'), ('REGEX_REPLACE', 'REGEX_REPLACE'), ('TRIM_SPACE', 'TRIM_SPACE'), ('REMOVE_TEXT_BEFORE_START_OF_TEXT', 'REMOVE_TEXT_BEFORE_START_OF_TEXT'), ('REMOVE_TEXT_BEFORE_END_OF_TEXT', 'REMOVE_TEXT_BEFORE_END_OF_TEXT'), ('REMOVE_TEXT_AFTER_START_OF_TEXT', 'REMOVE_TEXT_AFTER_START_OF_TEXT'), ('REMOVE_TEXT_AFTER_END_OF_TEXT', 'REMOVE_TEXT_AFTER_END_OF_TEXT'), ('REPLACE_TEXT', 'REPLACE_TEXT'), ('REPLACE_REGEX', 'REPLACE_REGEX'), ('JOIN_ALL_ROWS', 'JOIN_ALL_ROWS'), ('EXTRACT_FIRST_N_LINES', 'EXTRACT_FIRST_N_LINES'), ('EXTRACT_NTH_LINE', 'EXTRACT_NTH_LINE'), ('COMBINE_FIRST_N_LINES', 'COMBINE_FIRST_N_LINES'), ('GET_CHARS_FROM_NEXT_COL_IF_REGEX_NOT_MATCH', 'GET_CHARS_FROM_NEXT_COL_IF_REGEX_NOT_MATCH'), ('TRIM_SPACE_FOR_ALL_ROWS_AND_COLS', 'TRIM_SPACE_FOR_ALL_ROWS_AND_COLS'), ('REMOVE_ROWS_WITH_CONDITIONS', 'REMOVE_ROWS_WITH_CONDITIONS'), ('MERGE_ROWS_WITH_CONDITIONS', 'MERGE_ROWS_WITH_CONDITIONS'), ('MERGE_ROWS_WITH_SAME_COLUMNS', 'MERGE_ROWS_WITH_SAME_COLUMNS'), ('REMOVE_ROWS_BEFORE_ROW_WITH_CONDITIONS', 'REMOVE_ROWS_BEFORE_ROW_WITH_CONDITIONS'), ('REMOVE_ROWS_AFTER_ROW_WITH_CONDITIONS', 'REMOVE_ROWS_AFTER_ROW_WITH_CONDITIONS'), ('UNPIVOT_TABLE', 'UNPIVOT_TABLE'), ('MAKE_FIRST_ROW_TO_BE_HEADER', 'MAKE_FIRST_ROW_TO_BE_HEADER'), ('REMOVE_EMPTY_LINES', 'REMOVE_EMPTY_LINES'), ('CONVERT_TO_TABLE_BY_SPECIFY_HEADERS', 'CONVERT_TO_TABLE_BY_SPECIFY_HEADERS')], max_length=255)),
                ('remove_text', models.TextField(default='', max_length=1023, null=True)),
                ('remove_regex', models.TextField(default='', max_length=1023, null=True)),
                ('replace_text', models.TextField(default='', max_length=1023, null=True)),
                ('join_string', models.TextField(default='', max_length=1023, null=True)),
                ('extract_first_n_lines', models.IntegerField(default=1)),
                ('extract_nth_line', models.TextField(default='', null=True)),
                ('combine_first_n_lines', models.IntegerField(default=2)),
                ('get_chars_from_next_col_if_regex_not_match', models.TextField(default="{'col_index': '', 'regex': ''}", null=True)),
                ('remove_rows_with_conditions', models.TextField(default='[]', null=True)),
                ('merge_rows_with_conditions', models.TextField(default='[]', null=True)),
                ('merge_rows_with_same_columns', models.TextField(default='', null=True)),
                ('remove_rows_before_row_with_conditions', models.TextField(default="{'include_matched_row': True, 'conditions': [] }", null=True)),
                ('remove_rows_after_row_with_conditions', models.TextField(default="{'include_matched_row': True, 'conditions': [] }", null=True)),
                ('unpivot_table', models.TextField(default="{'col_index': '', 'assignment_separator': ':', 'new_line_separator': '\n' }", null=True)),
                ('convert_to_table_by_specify_headers', models.TextField(default='', null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='parsers.rule')),
            ],
        ),
    ]
