# Generated by Django 3.2.20 on 2023-08-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='convert_to_table_by_specify_headers',
        ),
        migrations.AlterField(
            model_name='stream',
            name='combine_first_n_lines',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='extract_nth_line',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='join_string',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='remove_regex',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='remove_text',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='replace_text',
            field=models.TextField(blank=True, default='', max_length=1023, null=True),
        ),
    ]
