# Generated by Django 3.2.20 on 2023-10-21 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_alter_queue_queue_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='pdf_version',
        ),
        migrations.AddField(
            model_name='integration',
            name='interval_seconds',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='next_run_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='integration',
            name='pdf_integration_type',
            field=models.CharField(choices=[('SOURCE', 'SOURCE'), ('PRE_PROCESSING', 'PRE_PROCESSING'), (
                'OCR', 'OCR'), ('POST_PROCESSING', 'POST_PROCESSING')], default='SOURCE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='integration',
            table=None,
        ),
    ]
