# Generated by Django 3.2.20 on 2023-10-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0015_auto_20231021_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProcessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_processing_type', models.CharField(choices=[('ROTATION_CORRECTION', 'ROTATION_CORRECTION')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_processings', to='parsers.parser')),
            ],
        ),
        migrations.CreateModel(
            name='PostProcessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_processing_type', models.CharField(choices=[('REDACTION', 'REDACTION')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('redaction_regex', models.CharField(max_length=1023, null=True)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postProcessings', to='parsers.parser')),
            ],
        ),
        migrations.AddField(
            model_name='integration',
            name='post_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_processing', to='parsers.postprocessing'),
        ),
        migrations.AddField(
            model_name='integration',
            name='pre_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_processing', to='parsers.preprocessing'),
        ),
    ]
