# Generated by Django 3.2.20 on 2023-08-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0015_auto_20230807_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='get_chars_from_next_col_if_regex_not_match',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='merge_rows_with_conditions',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='merge_rows_with_same_columns',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='remove_rows_after_row_with_conditions',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='remove_rows_before_row_with_conditions',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='remove_rows_with_conditions',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='unpivot_table',
        ),
    ]
