# Generated by Django 3.2.20 on 2023-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0016_auto_20231021_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='pdf_integration_type',
            field=models.CharField(choices=[('SOURCE', 'SOURCE'), ('PRE_PROCESSING', 'PRE_PROCESSING'), ('OCR', 'OCR'), ('POST_PROCESSING', 'POST_PROCESSING')], max_length=255, null=True),
        ),
    ]
