# Generated by Django 3.2.20 on 2023-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0016_auto_20230807_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_type',
            new_name='stream_class',
        ),
        migrations.AddField(
            model_name='stream',
            name='type',
            field=models.CharField(choices=[('TEXTFIELD', 'TEXTFIELD'), ('TABLE', 'TABLE')], default='TEXTFIELD', max_length=255),
            preserve_default=False,
        ),
    ]
