# Generated by Django 3.2.20 on 2023-10-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0017_alter_integration_pdf_integration_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integration',
            table='integrations',
        ),
        migrations.AlterModelTable(
            name='postprocessing',
            table='postprocessing',
        ),
        migrations.AlterModelTable(
            name='preprocessing',
            table='preprocessings',
        ),
    ]
