# Generated by Django 3.2.20 on 2023-08-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0018_auto_20230807_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='remove_regex',
            new_name='regex',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='remove_text',
            new_name='text',
        ),
    ]
