# Generated by Django 3.2.20 on 2023-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0018_auto_20231021_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='activated',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
