# Generated by Django 3.2.20 on 2023-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_integration_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprocessing',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
