# Generated by Django 3.2.20 on 2023-08-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_auto_20230807_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='replace_text',
        ),
    ]
