# Generated by Django 3.2.20 on 2023-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0020_postprocessing_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessing',
            name='pre_processing_type',
            field=models.CharField(choices=[('ORIENTATION_DETECTION', 'ORIENTATION_DETECTION')], max_length=255),
        ),
    ]
