# Generated by Django 3.2.20 on 2023-08-08 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0020_remove_stream_replace_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertToTableBySpecifyHeaders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_to_table_by_specify_headers_related', to='parsers.stream')),
            ],
        ),
    ]
