# Generated by Django 3.2.20 on 2023-10-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0021_alter_preprocessing_pre_processing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='ocr_image_layer_type',
            field=models.CharField(choices=[('SOURCE', 'SOURCE'), ('PREPROCESSING', 'PREPROCESSING')], default='SOURCE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocr',
            name='ocr_text_layer_type',
            field=models.CharField(choices=[('SOURCE', 'SOURCE'), ('PREPROCESSING', 'PREPROCESSING')], default='SOURCE', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postprocessing',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postprocessings', to='parsers.parser'),
        ),
        migrations.AlterField(
            model_name='preprocessing',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessings', to='parsers.parser'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_class',
            field=models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('IMPORT', 'IMPORT'), ('PREPROCESSING', 'PREPROCESSING'), ('OCR', 'OCR'), ('SPLITTING', 'SPLITTING'), ('PARSING', 'PARSING'), ('POSTPROCESSING', 'POSTPROCESSING'), ('INTEGRATION', 'INTEGRATION')], max_length=255),
        ),
    ]
