# Generated by Django 3.2.20 on 2023-08-08 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0021_converttotablebyspecifyheaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('header', models.TextField(default='', max_length=255, null=True)),
                ('convert_to_table_by_specify_headers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='parsers.converttotablebyspecifyheaders')),
            ],
        ),
    ]
