# Generated by Django 3.2.20 on 2023-08-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0022_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converttotablebyspecifyheaders',
            name='stream',
        ),
    ]
