# Generated by Django 3.2.20 on 2023-10-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0022_auto_20231024_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='post_processing',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='pre_processing',
        ),
        migrations.AddField(
            model_name='integration',
            name='postprocessing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postprocessing', to='parsers.postprocessing'),
        ),
        migrations.AddField(
            model_name='integration',
            name='preprocessing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing', to='parsers.preprocessing'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='image_layer_preprocessing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_layer_preprocessing', to='parsers.preprocessing'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='text_layer_preprocessing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_layer_preprocessing', to='parsers.preprocessing'),
        ),
    ]
