# Generated by Django 3.2.20 on 2023-10-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0023_auto_20231024_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='postprocessing',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='preprocessing',
        ),
        migrations.AddField(
            model_name='integration',
            name='post_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_processing', to='parsers.postprocessing'),
        ),
        migrations.AddField(
            model_name='integration',
            name='pre_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_processing', to='parsers.preprocessing'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_class',
            field=models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('IMPORT', 'IMPORT'), ('PRE_PROCESSING', 'PRE_PROCESSING'), ('OCR', 'OCR'), ('SPLITTING', 'SPLITTING'), ('PARSING', 'PARSING'), ('POST_PROCESSING', 'POST_PROCESSING'), ('INTEGRATION', 'INTEGRATION')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='postprocessing',
            table='post_processings',
        ),
        migrations.AlterModelTable(
            name='preprocessing',
            table='pre_processings',
        ),
    ]
