# Generated by Django 3.2.20 on 2023-10-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0024_auto_20231024_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='image_layer_preprocessing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_layer_preprocessing', to='parsers.preprocessing'),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='text_layer_preprocessing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_layer_preprocessing', to='parsers.preprocessing'),
        ),
    ]
