# Generated by Django 3.2.20 on 2023-08-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0024_stream_convert_to_table_by_specify_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='convert_to_table_by_specify_headers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parsers.converttotablebyspecifyheaders'),
        ),
    ]
