# Generated by Django 3.2.20 on 2023-08-08 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0026_alter_header_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=256),
        ),
        migrations.AlterField(
            model_name='header',
            name='header',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
