# Generated by Django 3.2.20 on 2023-10-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0027_auto_20231026_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='postprocessing',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='preprocessing',
        ),
        migrations.AddField(
            model_name='integration',
            name='post_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_processing', to='parsers.postprocessing'),
        ),
        migrations.AddField(
            model_name='integration',
            name='pre_processing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_processing', to='parsers.preprocessing'),
        ),
    ]
