# Generated by Django 3.2.20 on 2023-08-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0028_alter_stream_convert_to_table_by_specify_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='convert_to_table_by_specify_headers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='parsers.converttotablebyspecifyheaders'),
        ),
    ]
