# Generated by Django 3.2.20 on 2023-10-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0028_auto_20231026_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittingcondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('REGEX', 'REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='splittingrule',
            name='route_to_parser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.parser'),
        ),
    ]
