# Generated by Django 3.2.23 on 2023-11-03 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0029_auto_20231030_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitting',
            name='no_first_page_rules_matched_operation_type',
            field=models.CharField(choices=[('REMOVE_THE_PAGE', 'REMOVE_THE_PAGE'), ('CONTINUE_PARSING', 'CONTINUE_PARSING'), ('ROUTE_TO_PARSER', 'ROUTE_TO_PARSER')], default='REMOVE_THE_PAGE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='splitting',
            name='no_first_page_rules_matched_route_to_parser',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='no_first_page_rules_matched_route_to_parser', to='parsers.parser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='splitting',
            name='parser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parser', to='parsers.parser'),
        ),
    ]
