# Generated by Django 3.2.20 on 2023-08-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0029_alter_header_convert_to_table_by_specify_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumnSeparator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_column_separators', to='parsers.rule')),
            ],
        ),
    ]
