# Generated by Django 3.2.23 on 2023-11-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0030_auto_20231103_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitting',
            name='no_first_page_rules_matched_route_to_parser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_first_page_rules_matched_route_to_parser', to='parsers.parser'),
        ),
    ]
