# Generated by Django 3.2.20 on 2023-08-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0030_tablecolumnseparator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='documentpage',
            table='document_pages',
        ),
        migrations.AlterModelTable(
            name='parser',
            table='parsers',
        ),
        migrations.AlterModelTable(
            name='queue',
            table='queues',
        ),
        migrations.AlterModelTable(
            name='routingcondition',
            table='routing_conditions',
        ),
        migrations.AlterModelTable(
            name='routingrule',
            table='routing_rules',
        ),
        migrations.AlterModelTable(
            name='rule',
            table='rules',
        ),
        migrations.AlterModelTable(
            name='stream',
            table='streams',
        ),
        migrations.AlterModelTable(
            name='tablecolumnseparator',
            table='table_column_separators',
        ),
    ]
