# Generated by Django 3.2.23 on 2023-11-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0031_alter_splitting_no_first_page_rules_matched_route_to_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitting',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
