# Generated by Django 3.2.20 on 2023-08-29 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0031_auto_20230829_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=1023)),
                ('interval_seconds', models.IntegerField()),
                ('next_run_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated', models.BooleanField(default=True)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='parsers.parser')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
    ]
