# Generated by Django 3.2.20 on 2023-08-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0032_source'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='converttotablebyspecifyheaders',
            table='convert_to_table_by_specify_headers',
        ),
        migrations.AlterModelTable(
            name='header',
            table='headers',
        ),
    ]
