# Generated by Django 3.2.23 on 2023-11-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0033_aichat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aichat',
            table='aichats',
        ),
    ]
