# Generated by Django 3.2.23 on 2023-11-10 02:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0034_alter_aichat_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('chatbot_type', models.CharField(choices=[('NO_CHATBOT', 'NO_CHATBOT'), ('OPEN_AI', 'OPEN_AI')], default='NO_CHATBOT', max_length=255, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('open_ai_api_key', models.CharField(max_length=1024, null=True)),
                ('parser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='parsers.parser')),
            ],
            options={
                'db_table': 'chatbots',
            },
        ),
        migrations.CreateModel(
            name='OpenAI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('open_ai_api_key', models.CharField(max_length=1024, null=True)),
                ('parser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_ai', to='parsers.parser')),
            ],
            options={
                'db_table': 'open_ais',
            },
        ),
        migrations.AlterField(
            model_name='queue',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='parsers.document'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_class',
            field=models.CharField(choices=[('PROCESSED', 'PROCESSED'), ('IMPORT', 'IMPORT'), ('PRE_PROCESSING', 'PRE_PROCESSING'), ('OCR', 'OCR'), ('SPLITTING', 'SPLITTING'), ('AICHAT', 'AICHAT'), ('PARSING', 'PARSING'), ('POST_PROCESSING', 'POST_PROCESSING'), ('INTEGRATION', 'INTEGRATION')], max_length=255),
        ),
        migrations.DeleteModel(
            name='AIChat',
        ),
    ]
