# Generated by Django 3.2.23 on 2023-11-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0035_auto_20231110_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='ocr',
            name='google_vision_ocr_api_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='openai',
            name='open_ai_api_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
