# Generated by Django 3.2.23 on 2023-11-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0037_stream_open_ai_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_resource_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='openai',
            name='open_ai_resource_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
