# Generated by Django 3.2.23 on 2023-11-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0038_auto_20231110_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='ocred',
            field=models.BooleanField(default=False),
        ),
    ]
