# Generated by Django 3.2.23 on 2023-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0039_documentpage_ocred'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_default_question',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
