# Generated by Django 3.2.23 on 2023-11-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0040_chatbot_open_ai_default_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='chatbot_completed',
            field=models.BooleanField(default=False),
        ),
    ]
