# Generated by Django 3.2.23 on 2023-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0041_documentpage_chatbot_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='total_page_num',
            field=models.IntegerField(null=True),
        ),
    ]
