# Generated by Django 3.2.23 on 2023-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0043_alter_stream_stream_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.CharField(choices=[('TEXTFIELD', 'TEXTFIELD'), ('TABLE', 'TABLE'), ('ACROBAT_FORM', 'ACROBAT_FORM')], max_length=256),
        ),
    ]
