# Generated by Django 3.2.23 on 2023-11-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0044_alter_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='anchor_relative_x1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='anchor_relative_x2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='anchor_relative_y1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='anchor_relative_y2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
