# Generated by Django 3.2.23 on 2023-11-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0045_auto_20231122_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='anchor_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='parsers.document'),
        ),
        migrations.AddField(
            model_name='rule',
            name='anchor_page_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
