# Generated by Django 3.2.23 on 2023-11-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0046_auto_20231123_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='anchor_page_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_relative_x1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_relative_x2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_relative_y1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_relative_y2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_x1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_x2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_y1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_y2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='x1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='x2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='y1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='y2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
