# Generated by Django 3.2.23 on 2023-11-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0047_auto_20231123_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='xml',
            field=models.TextField(default='<?xml version="1.0" encoding="utf-8" ?>'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='anchor_text',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
