# Generated by Django 3.2.23 on 2023-11-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0048_auto_20231123_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='paddle_ocr_language',
            field=models.CharField(blank=True, default='cn', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='ocr_type',
            field=models.CharField(choices=[('NO_OCR', 'NO_OCR'), ('GOOGLE_VISION', 'GOOGLE_VISION'), ('DOCTR', 'DOCTR'), ('PADDLE_OCR', 'PADDLE_OCR')], default='NO_OCR', max_length=255, null=True),
        ),
    ]
