# Generated by Django 3.2.23 on 2023-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0049_auto_20231124_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_extension',
            field=models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('GIF', 'GIF'), ('TIFF', 'TIFF')], default='PDF', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('TEMPALTE', 'TEMPALTE'), ('IMPORT', 'IMPORT')], max_length=255),
        ),
    ]
