# Generated by Django 3.2.23 on 2023-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0050_auto_20231124_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('TEMPLATE', 'TEMPLATE'), ('IMPORT', 'IMPORT')], max_length=255),
        ),
    ]
