# Generated by Django 3.2.23 on 2023-11-28 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0052_auto_20231128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
