# Generated by Django 3.2.23 on 2023-11-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0053_source_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
