# Generated by Django 3.2.23 on 2023-11-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0054_source_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='image_file',
        ),
    ]
