# Generated by Django 3.2.23 on 2023-12-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0057_auto_20231206_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_status',
            field=models.CharField(choices=[('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('STOPPED', 'STOPPED'), ('COMPLETED', 'COMPLETED'), ('TERMINATED_AFTER_TRIAL', 'TERMINATED_AFTER_TRIAL')], default='READY', max_length=255),
        ),
    ]
