# Generated by Django 3.2.23 on 2023-12-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0058_alter_queue_queue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_deployment',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
