# Generated by Django 3.2.23 on 2023-12-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0059_chatbot_open_ai_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='openai',
            name='open_ai_deployment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
