# Generated by Django 3.2.23 on 2023-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0061_alter_splittingcondition_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='omnipage_ocr_language',
            field=models.CharField(blank=True, default='LANG_ENG', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='ocr_type',
            field=models.CharField(choices=[('NO_OCR', 'NO_OCR'), ('GOOGLE_VISION', 'GOOGLE_VISION'), ('DOCTR', 'DOCTR'), ('PADDLE_OCR', 'PADDLE_OCR'), ('OMNIPAGE_OCR', 'OMNIPAGE_OCR')], default='NO_OCR', max_length=255, null=True),
        ),
    ]
