# Generated by Django 3.2.23 on 2023-12-22 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0062_auto_20231218_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splittingrule',
            name='parent_splitting_rule',
        ),
        migrations.AlterField(
            model_name='splittingrule',
            name='splitting_rule_type',
            field=models.CharField(choices=[('FIRST_PAGE', 'FIRST_PAGE'), ('CONSECUTIVE_PAGE', 'CONSECUTIVE_PAGE'), ('LAST_PAGE', 'LAST_PAGE')], max_length=255),
        ),
        migrations.CreateModel(
            name='LastPageSplittingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('splitting_rule_type', models.CharField(choices=[('FIRST_PAGE', 'FIRST_PAGE'), ('CONSECUTIVE_PAGE', 'CONSECUTIVE_PAGE'), ('LAST_PAGE', 'LAST_PAGE')], max_length=255)),
                ('sort_order', models.IntegerField()),
                ('parent_splitting_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_page_splitting_rules', to='parsers.splittingrule')),
                ('route_to_parser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
                ('splitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='parsers.splitting')),
            ],
            options={
                'db_table': 'last_page_splitting_rules',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivePageSplittingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('splitting_rule_type', models.CharField(choices=[('FIRST_PAGE', 'FIRST_PAGE'), ('CONSECUTIVE_PAGE', 'CONSECUTIVE_PAGE'), ('LAST_PAGE', 'LAST_PAGE')], max_length=255)),
                ('sort_order', models.IntegerField()),
                ('parent_splitting_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consecutive_page_splitting_rules', to='parsers.splittingrule')),
                ('route_to_parser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
                ('splitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitting_rules', to='parsers.splitting')),
            ],
            options={
                'db_table': 'consecutive_page_splitting_rules',
            },
        ),
    ]
