# Generated by Django 3.2.23 on 2023-12-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0063_auto_20231222_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consecutivepagesplittingrule',
            name='route_to_parser',
        ),
        migrations.RemoveField(
            model_name='consecutivepagesplittingrule',
            name='splitting',
        ),
        migrations.RemoveField(
            model_name='lastpagesplittingrule',
            name='route_to_parser',
        ),
        migrations.RemoveField(
            model_name='lastpagesplittingrule',
            name='splitting',
        ),
    ]
