# Generated by Django 3.2.23 on 2024-01-24 04:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0067_auto_20240123_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consecutivepagesplittingrule',
            name='splitting_rule_type',
        ),
        migrations.RemoveField(
            model_name='lastpagesplittingrule',
            name='splitting_rule_type',
        ),
        migrations.CreateModel(
            name='LastPageSplittingCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('DOES_NOT_CONTAINS', 'DOES_NOT_CONTAINS'), ('REGEX', 'REGEX'), ('NOT_REGEX', 'NOT_REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('last_page_routing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_page_splitting_conditions', to='parsers.lastpagesplittingrule')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.rule')),
            ],
            options={
                'db_table': 'last_page_splitting_conditions',
            },
        ),
        migrations.CreateModel(
            name='ConsecutivePageSplittingCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('DOES_NOT_CONTAINS', 'DOES_NOT_CONTAINS'), ('REGEX', 'REGEX'), ('NOT_REGEX', 'NOT_REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED')], max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField()),
                ('consecutive_routing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecutive_page_splitting_conditions', to='parsers.consecutivepagesplittingrule')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.rule')),
            ],
            options={
                'db_table': 'consecutive_page_splitting_conditions',
            },
        ),
    ]
