# Generated by Django 3.2.23 on 2024-02-15 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0069_auto_20240124_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_metrics_client_id',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_metrics_client_secret',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_metrics_service_name',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_metrics_subscription_id',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_metrics_tenant_id',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='splittingcondition',
            name='consecutive_page_splitting_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consecutive_page_splitting_rules', to='parsers.consecutivepagesplittingrule'),
        ),
        migrations.AlterField(
            model_name='splittingcondition',
            name='last_page_splitting_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_page_splitting_rules', to='parsers.lastpagesplittingrule'),
        ),
    ]
