# Generated by Django 3.2.23 on 2024-02-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0070_auto_20240215_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='open_ai_metrics_client_id',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='open_ai_metrics_client_secret',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='open_ai_metrics_service_name',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='open_ai_metrics_subscription_id',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='open_ai_metrics_tenant_id',
        ),
    ]
