# Generated by Django 3.2.23 on 2024-02-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0071_auto_20240215_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIMetricsKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_ai_metrics_tenant_id', models.CharField(default='', max_length=1024, null=True)),
                ('open_ai_metrics_client_id', models.CharField(default='', max_length=1024, null=True)),
                ('open_ai_metrics_client_secret', models.CharField(default='', max_length=1024, null=True)),
                ('open_ai_metrics_subscription_id', models.CharField(default='', max_length=1024, null=True)),
                ('open_ai_metrics_service_name', models.CharField(default='', max_length=1024, null=True)),
                ('parser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_ai_metrics_key', to='parsers.parser')),
            ],
            options={
                'db_table': 'open_ai_metrics_key',
            },
        ),
    ]
