# Generated by Django 3.2.23 on 2024-02-15 03:23

from django.db import migrations

def set_initial_open_ai_metrics_key(apps, schema_editor):
    Parser = apps.get_model("parsers", "Parser")
    OpenAIMetricsKey = apps.get_model("parsers", "OpenAIMetricsKey")

    parsers = Parser.objects.all()

    for parser in parsers:
        open_ai_metrics_key = OpenAIMetricsKey()
        open_ai_metrics_key.parser = parser
        open_ai_metrics_key.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0072_openaimetricskeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIMetricsKeys',
            new_name='OpenAIMetricsKey',
        ),
        migrations.RunPython(set_initial_open_ai_metrics_key, migrations.RunPython.noop)
    ]
