# Generated by Django 3.2.23 on 2024-02-15 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0073_rename_openaimetricskeys_openaimetricskey'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_tokens', models.IntegerField()),
                ('generated_tokens', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'db_table': 'open_ai_metrics',
            },
        ),
    ]
