# Generated by Django 3.2.23 on 2024-02-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0076_parser_total_num_of_pages_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='debug',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='ocr_type',
            field=models.CharField(choices=[('NO_OCR', 'NO_OCR'), ('GOOGLE_VISION', 'GOOGLE_VISION'), ('DOCTR', 'DOCTR'), ('PADDLE', 'PADDLE'), ('OMNIPAGE', 'OMNIPAGE')], default='NO_OCR', max_length=255, null=True),
        ),
    ]
