# Generated by Django 3.2.23 on 2024-02-27 08:56

from django.db import migrations, models
import django.db.models.deletion


def set_orientation_detection(apps, schema_editor):
    PreProcessing = apps.get_model("parsers", "PreProcessing")

    preProcessings = PreProcessing.objects.filter(pre_processing_type="ORIENTATION_DETECTION").all()

    for preProcessing in preProcessings:
        preProcessing.pre_processing_type = "ORIENTATION_DETECTION_TESSERACT"
        preProcessing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0077_auto_20240221_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessing',
            name='debug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preprocessing',
            name='orientation_detection_tesseract_confidence_above',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='openaimetricskey',
            name='parser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_ai_metrics_key', to='parsers.parser'),
        ),
        migrations.AlterField(
            model_name='preprocessing',
            name='pre_processing_type',
            field=models.CharField(choices=[('ORIENTATION_DETECTION_OPENCV', 'ORIENTATION_DETECTION_OPENCV'), ('ORIENTATION_DETECTION_TESSERACT', 'ORIENTATION_DETECTION_TESSERACT'), ('THRESHOLD_BINARIZATION', 'THRESHOLD_BINARIZATION')], max_length=255),
        ),
        migrations.RunPython(set_orientation_detection, migrations.RunPython.noop)
    ]
