# Generated by Django 3.2.23 on 2024-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0078_auto_20240227_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessing',
            name='pre_processing_type',
            field=models.CharField(choices=[('ORIENTATION_DETECTION_OPENCV', 'ORIENTATION_DETECTION_OPENCV'), ('ORIENTATION_DETECTION_TESSERACT', 'ORIENTATION_DETECTION_TESSERACT'), ('ORIENTATION_DETECTION_DOCTR', 'ORIENTATION_DETECTION_DOCTR'), ('THRESHOLD_BINARIZATION', 'THRESHOLD_BINARIZATION')], max_length=255),
        ),
    ]
