# Generated by Django 3.2.23 on 2024-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0079_alter_preprocessing_pre_processing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('TEMPLATE', 'TEMPLATE'), ('IMPORT', 'IMPORT'), ('AICHAT', 'AICHAT'), ('TRASH', 'TRASH')], max_length=255),
        ),
    ]
