# Generated by Django 3.2.23 on 2024-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0080_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='splitted',
            field=models.BooleanField(default=False),
        ),
    ]
