# Generated by Django 3.2.23 on 2024-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0081_document_splitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='acrobat_form_field',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
