# Generated by Django 3.2.23 on 2024-03-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0083_auto_20240314_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splittingcondition',
            name='consecutive_page_splitting_rule',
        ),
        migrations.RemoveField(
            model_name='splittingcondition',
            name='last_page_splitting_rule',
        ),
    ]
