# Generated by Django 3.2.23 on 2024-03-14 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0084_auto_20240314_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
