# Generated by Django 3.2.25 on 2024-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0086_ocr_detect_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='assumed_text_height',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parser',
            name='assumed_text_width',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parser',
            name='same_column_acceptance_range',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parser',
            name='same_line_acceptance_range',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=10, null=True),
        ),
    ]
