# Generated by Django 3.2.25 on 2024-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0087_auto_20240320_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='pdf_to_image_dpi',
            field=models.DecimalField(decimal_places=0, default=300, max_digits=10, null=True),
        ),
    ]
