# Generated by Django 3.2.25 on 2024-04-05 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsers', '0089_rename_user_parser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='permitted_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='parser',
            name='permitted_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
