# Generated by Django 3.2.25 on 2024-04-05 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parsers', '0091_auto_20240405_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='permitted_groups',
            field=models.ManyToManyField(related_name='group_permitted_parsers', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='permitted_users',
            field=models.ManyToManyField(related_name='user_permitted_parsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
