# Generated by Django 3.2.25 on 2024-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0095_auto_20240405_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.CharField(choices=[('TEXTFIELD', 'TEXTFIELD'), ('TABLE', 'TABLE'), ('ACROBAT_FORM', 'ACROBAT_FORM'), ('JSON', 'JSON')], max_length=256),
        ),
    ]
