# Generated by Django 3.2.25 on 2024-04-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0097_auto_20240410_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='depends_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depending_rules', to='parsers.rule'),
        ),
    ]
