# Generated by Django 3.2.25 on 2024-04-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0099_auto_20240416_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutivepagesplittingrule',
            name='consecutive_page_splitting_rule_type',
            field=models.CharField(choices=[('BY_CONDITIONS', 'BY_CONDITIONS'), ('WHEN_OTHER_FIRST_PAGE_SPLITTING_RULES_DO_NOT_MATCH', 'WHEN_OTHER_FIRST_PAGE_SPLITTING_RULES_DO_NOT_MATCH')], default='BY_CONDITIONS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastpagesplittingrule',
            name='last_page_splitting_rule_type',
            field=models.CharField(choices=[('BY_CONDITIONS', 'BY_CONDITIONS'), ('WHEN_OTHER_FIRST_PAGE_SPLITTING_RULES_MATCH', 'WHEN_OTHER_FIRST_PAGE_SPLITTING_RULES_MATCH')], default='BY_CONDITIONS', max_length=255, null=True),
        ),
    ]
