# Generated by Django 3.2.25 on 2024-06-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0101_auto_20240423_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='open_ai_default_question',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
