# Generated by Django 3.2.25 on 2024-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0102_alter_chatbot_open_ai_default_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivepagesplittingcondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('DOES_NOT_CONTAINS', 'DOES_NOT_CONTAINS'), ('REGEX', 'REGEX'), ('NOT_REGEX', 'NOT_REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED'), ('ALWAYS_TRUE', 'ALWAYS_TRUE'), ('ALWAYS_FALSE', 'ALWAYS_FALSE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lastpagesplittingcondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('DOES_NOT_CONTAINS', 'DOES_NOT_CONTAINS'), ('REGEX', 'REGEX'), ('NOT_REGEX', 'NOT_REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED'), ('ALWAYS_TRUE', 'ALWAYS_TRUE'), ('ALWAYS_FALSE', 'ALWAYS_FALSE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='splittingcondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'EQUALS'), ('CONTAINS', 'CONTAINS'), ('DOES_NOT_CONTAINS', 'DOES_NOT_CONTAINS'), ('REGEX', 'REGEX'), ('NOT_REGEX', 'NOT_REGEX'), ('IS_EMPTY', 'IS_EMPTY'), ('IS_NOT_EMPTY', 'IS_NOT_EMPTY'), ('CHANGED', 'CHANGED'), ('NOT_CHANGED', 'NOT_CHANGED'), ('ALWAYS_TRUE', 'ALWAYS_TRUE'), ('ALWAYS_FALSE', 'ALWAYS_FALSE')], max_length=255),
        ),
    ]
