# Generated by Django 3.2.25 on 2024-06-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0103_auto_20240617_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='chatbot_completed',
        ),
    ]
