# Generated by Django 3.2.25 on 2024-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0105_alter_ocr_ocr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='apple_vision_ocr_language',
            field=models.CharField(blank=True, default='en-US', max_length=256, null=True),
        ),
    ]
