# Generated by Django 3.2.20 on 2023-07-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=1023)),
                ('company_name', models.TextField(blank=True, max_length=1023)),
                ('country', models.CharField(blank=True, choices=[('A', 'F'), ('A', 'X'), ('A', 'L'), ('D', 'Z'), ('A', 'S'), ('A', 'D'), ('A', 'O'), ('A', 'I'), ('A', 'Q'), ('A', 'G'), ('A', 'R'), ('A', 'M'), ('A', 'W'), ('A', 'U'), ('A', 'T'), ('A', 'Z'), ('B', 'S'), ('B', 'H'), ('B', 'D'), ('B', 'B'), ('B', 'Y'), ('B', 'E'), ('B', 'Z'), ('B', 'J'), ('B', 'M'), ('B', 'T'), ('B', 'O'), ('B', 'A'), ('B', 'W'), ('B', 'V'), ('B', 'R'), ('I', 'O'), ('V', 'G'), ('B', 'N'), ('B', 'G'), ('B', 'F'), ('B', 'I'), ('K', 'H'), ('C', 'M'), ('C', 'A'), ('C', 'V'), ('B', 'Q'), ('K', 'Y'), ('C', 'F'), ('T', 'D'), ('C', 'L'), ('C', 'N'), ('C', 'X'), ('C', 'C'), ('C', 'O'), ('K', 'M'), ('C', 'G'), ('C', 'D'), ('C', 'K'), ('C', 'R'), ('C', 'I'), ('H', 'R'), ('C', 'U'), ('C', 'W'), ('C', 'Y'), ('C', 'Z'), ('D', 'K'), ('D', 'J'), ('D', 'M'), ('D', 'O'), ('E', 'C'), ('E', 'G'), ('S', 'V'), ('G', 'Q'), ('E', 'R'), ('E', 'E'), ('S', 'Z'), ('E', 'T'), ('F', 'K'), ('F', 'O'), ('F', 'J'), ('F', 'I'), ('F', 'R'), ('G', 'F'), ('P', 'F'), ('T', 'F'), ('G', 'A'), ('G', 'M'), ('G', 'E'), ('D', 'E'), ('G', 'H'), ('G', 'I'), ('G', 'R'), ('G', 'L'), ('G', 'D'), ('G', 'P'), ('G', 'U'), ('G', 'T'), ('G', 'G'), ('G', 'N'), ('G', 'W'), ('G', 'Y'), ('H', 'T'), ('H', 'M'), ('H', 'N'), ('H', 'K'), ('H', 'U'), ('I', 'S'), ('I', 'N'), ('I', 'D'), ('I', 'R'), ('I', 'Q'), ('I', 'E'), ('I', 'M'), ('I', 'L'), ('I', 'T'), ('J', 'M'), ('J', 'P'), ('J', 'E'), ('J', 'O'), ('K', 'Z'), ('K', 'E'), ('K', 'I'), ('K', 'W'), ('K', 'G'), ('L', 'A'), ('L', 'V'), ('L', 'B'), ('L', 'S'), ('L', 'R'), ('L', 'Y'), ('L', 'I'), ('L', 'T'), ('L', 'U'), ('M', 'O'), ('M', 'G'), ('M', 'W'), ('M', 'Y'), ('M', 'V'), ('M', 'L'), ('M', 'T'), ('M', 'H'), ('M', 'Q'), ('M', 'R'), ('M', 'U'), ('Y', 'T'), ('M', 'X'), ('F', 'M'), ('M', 'D'), ('M', 'C'), ('M', 'N'), ('M', 'E'), ('M', 'S'), ('M', 'A'), ('M', 'Z'), ('M', 'M'), ('N', 'A'), ('N', 'R'), ('N', 'P'), ('N', 'L'), ('N', 'C'), ('N', 'Z'), ('N', 'I'), ('N', 'E'), ('N', 'G'), ('N', 'U'), ('N', 'F'), ('K', 'P'), ('M', 'K'), ('M', 'P'), ('N', 'O'), ('O', 'M'), ('P', 'K'), ('P', 'W'), ('P', 'S'), ('P', 'A'), ('P', 'G'), ('P', 'Y'), ('P', 'E'), ('P', 'H'), ('P', 'N'), ('P', 'L'), ('P', 'T'), ('P', 'R'), ('Q', 'A'), ('R', 'E'), ('R', 'O'), ('R', 'U'), ('R', 'W'), ('W', 'S'), ('S', 'M'), ('S', 'T'), ('S', 'A'), ('S', 'N'), ('R', 'S'), ('S', 'C'), ('S', 'L'), ('S', 'G'), ('S', 'X'), ('S', 'K'), ('S', 'I'), ('S', 'B'), ('S', 'O'), ('Z', 'A'), ('G', 'S'), ('K', 'R'), ('S', 'S'), ('E', 'S'), ('L', 'K'), ('B', 'L'), ('S', 'H'), ('K', 'N'), ('L', 'C'), ('M', 'F'), ('P', 'M'), ('V', 'C'), ('S', 'D'), ('S', 'R'), ('S', 'J'), ('S', 'E'), ('C', 'H'), ('S', 'Y'), ('T', 'W'), ('T', 'J'), ('T', 'Z'), ('T', 'H'), ('T', 'L'), ('T', 'G'), ('T', 'K'), ('T', 'O'), ('T', 'T'), ('T', 'N'), ('T', 'R'), ('T', 'M'), ('T', 'C'), ('T', 'V'), ('U', 'M'), ('V', 'I'), ('U', 'G'), ('U', 'A'), ('A', 'E'), ('G', 'B'), ('U', 'S'), ('U', 'Y'), ('U', 'Z'), ('V', 'U'), ('V', 'A'), ('V', 'E'), ('V', 'N'), ('W', 'F'), ('E', 'H'), ('Y', 'E'), ('Z', 'M'), ('Z', 'W')], max_length=1023)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
